- hosts: localhost
  tasks:
    - name: custom module
      test-hunter.py:
        input: "Goodbye Mitesh,Thanks for your teaching"
        print1: "{{ key }}"
      register: output

    - debug: var=output

    - name: Diskspace module
      diskspace: 
        path: /
        storage: true
      register: output

    - debug: var=output

